[tool.mypy]
strict = true
show_error_codes = true
enable_error_code = "ignore-without-code"

[tool.pylint]
load-plugins=[
    "pylint.extensions.check_elif",
    "pylint.extensions.code_style",
    "pylint.extensions.comparetozero",
    "pylint.extensions.confusing_elif",
    "pylint.extensions.docparams",
    "pylint.extensions.docstyle",
    "pylint.extensions.empty_comment",
    "pylint.extensions.for_any_all",
    "pylint.extensions.set_membership",
    "pylint.extensions.typing"
]
py-version="3.11"
disable = [
    "missing-module-docstring",
    "missing-function-docstring",
    "too-few-public-methods",
    "duplicate-code"
]
enable = [
    "c-extension-no-member",
]
no-docstring-rgx = "__.*__"

[tool.isort]
profile = "black"

[tool.black]
quiet = true
